# Generated by Django 4.2 on 2023-04-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_no', models.CharField(max_length=20)),
                ('department_name', models.CharField(max_length=20)),
            ],
        ),
    ]
