# Generated by Django 4.2 on 2023-04-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.AlterField(
            model_name='department',
            name='department_no',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
