# Generated by Django 4.2 on 2023-04-18 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_project_employee_departmentlocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='department_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.department'),
        ),
    ]
